#!/bin/sh
set -eu

###########################
######## CONFIG ###########
###########################
SOURCE_PROJ=app
GROUP_ID_ARTIFACT_ID="com.viliussutkus89:SampleAppToTestUnitTests"
PACKAGE_ID="com.viliussutkus89.sampleapptotestunittests"
PACKAGE_FOLDER_PATH="com/viliussutkus89/sampleapptotestunittests"
###########################
##### ~~~CONFIG~~~ ########
###########################

BASEDIR=$(dirname "$0")/..

#cat $BASEDIR/build.gradle
sed -E "/repositories/a mavenLocal/" $BASEDIR/build.gradle
#sed -i'.orig' -E "/repositories \{/a mavenLocal()" $BASEDIR/build.gradle
#cat $BASEDIR/build.gradle
exit 0
sed -i'.orig' -E "s/include(.*)/include\1, ':aar-instrumented-tests'/g" $BASEDIR/settings.gradle

DST=$BASEDIR/aar-instrumented-tests
function copy() {
  local TARGET=$1
  local DST_DIR=$DST/$(dirname $TARGET)

  mkdir -p $DST_DIR
  cp -r $BASEDIR/$SOURCE_PROJ/$TARGET $DST_DIR/
}

copy build.gradle
sed -i'.orig' -E "/dependencies \{/a implementation '${GROUP_ID_ARTIFACT_ID}:+'" $DST/build.gradle

copy src/main/AndroidManifest.xml
sed -i'.orig' -E "s/package\=\"(.*)\"/package\=\"\1.aarinstrumentedtests\"/g" $DST/src/main/AndroidManifest.xml

copy src/androidTest
find $DST/src/androidTest -type f -name '*.java' -exec sed -i'.orig' -E "s/package (.*)\;/package \1.aarinstrumentedtests\;\nimport \1\.\*\;/g" {} \;

mkdir $DST/src/androidTest/java/$PACKAGE_FOLDER_PATH/aarinstrumentedtests
find $DST/src/androidTest/java/$PACKAGE_FOLDER_PATH -type f -name '*.java' -exec mv {} $DST/src/androidTest/java/$PACKAGE_FOLDER_PATH/aarinstrumentedtests/ \;
