#!/bin/sh
set -eu

###########################
######## CONFIG ###########
###########################
SOURCE_PROJ=app
GROUP_ID_ARTIFACT_ID="com.viliussutkus89:SampleAppToTestUnitTests"
PACKAGE_ID="com.viliussutkus89.sampleapptotestunittests"
PACKAGE_FOLDER_PATH="com/viliussutkus89/sampleapptotestunittests"
###########################
##### ~~~CONFIG~~~ ########
###########################

BASEDIR=$(dirname "$0")/..
cd $BASEDIR

sed -i'.orig' -E "s/repositories \{/repositories \{\nmavenLocal()/g" ./build.gradle
rm ./build.gradle.orig
#@TODO: STAGING
cat ./build.gradle

sed -i'.orig' -E "s/include(.*)/include\1, ':aar-instrumented-tests'/g" ./settings.gradle
rm ./settings.gradle.orig
cat ./settings.gradle

DST=./aar-instrumented-tests
function copy() {
  local TARGET=$1
  local DST_DIR=$DST/$(dirname $TARGET)

  mkdir -p $DST_DIR
  cp -r ./$SOURCE_PROJ/$TARGET $DST_DIR/
}


copy build.gradle
sed -i'.orig' -E "s/dependencies {/implementation { '${GROUP_ID_ARTIFACT_ID}:+'/g" $DST/build.gradle
rm $DST/build.gradle.orig
#@TODO: STAGING
cat $DST/build.gradle

copy src/main/AndroidManifest.xml
sed -i'.orig' -E "s/package\=\"(.*)\"/package\=\"\1.aarinstrumentedtests\"/g" $DST/src/main/AndroidManifest.xml
rm $DST/src/main/AndroidManifest.xml.orig
#@TODO: STAGING
cat $DST/src/main/AndroidManifest.xml

copy src/androidTest
find $DST/src/androidTest -type f -name '*.java' -exec sed -i'.orig' -E "s/package (.*)\;/package \1.aarinstrumentedtests\;\nimport \1\.\*\;/g" {} \;
find $DST/src/androidTest -type f -name '*.java.orig' -exec rm {} \;

mkdir $DST/src/androidTest/java/$PACKAGE_FOLDER_PATH/aarinstrumentedtests
find $DST/src/androidTest/java/$PACKAGE_FOLDER_PATH -type f -name '*.java' -exec mv {} $DST/src/androidTest/java/$PACKAGE_FOLDER_PATH/aarinstrumentedtests/ \;
