#!/bin/sh
set -eu

###########################
######## CONFIG ###########
###########################
SOURCE_PROJ=app
GROUP_ID_ARTIFACT_ID="com.viliussutkus89:SampleAppToTestUnitTests"
PACKAGE_ID="com.viliussutkus89.sampleapptotestunittests"
PACKAGE_FOLDER_PATH="com/viliussutkus89/sampleapptotestunittests"
###########################
##### ~~~CONFIG~~~ ########
###########################

BASEDIR=$(dirname "$0")/..

sed -E "/repositories \{/a \ \ \ \ \ \ \ \ mavenLocal()" -i $BASEDIR/build.gradle

sed -E "s/include(.*)/include\1, ':aar-instrumented-tests'/g" -i $BASEDIR/settings.gradle

DST=$BASEDIR/aar-instrumented-tests
function copy() {
  local TARGET=$1
  local DST_DIR=$DST/$(dirname $TARGET)

  mkdir -p $DST_DIR
  cp -r $BASEDIR/$SOURCE_PROJ/$TARGET $DST_DIR/
}

copy build.gradle
sed -E "/dependencies \{/a \ \ \ \ implementation '${GROUP_ID_ARTIFACT_ID}:+'" -i $DST/build.gradle

copy src/main/AndroidManifest.xml
sed -E "s/package\=\"(.*)\"/package\=\"\1.aarinstrumentedtests\"/g" -i $DST/src/main/AndroidManifest.xml

copy src/androidTest
find $DST/src/androidTest -type f -name '*.java' -exec sed -E "s/package (.*)\;/package \1.aarinstrumentedtests\;\nimport \1\.\*\;/g" -i {} \;

mkdir $DST/src/androidTest/java/$PACKAGE_FOLDER_PATH/aarinstrumentedtests
find $DST/src/androidTest/java/$PACKAGE_FOLDER_PATH -type f -name '*.java' -exec mv {} $DST/src/androidTest/java/$PACKAGE_FOLDER_PATH/aarinstrumentedtests/ \;
