name: android
on: push
jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: ViliusSutkus89/setup-android@release

    - run: sdkmanager "cmdline-tools;latest"
      
    - run: sdkmanager "cmdline-tools;3.0"
      
    - run: ./gradlew build
