name: android
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: ViliusSutkus89/setup-android@release

    - run: ./gradlew assembleRelease

    - run: ./gradlew publishToMavenLocal

    - uses: actions/upload-artifact@v2
      with:
        name: maven-local
        path: ~/.m2

  runInstrumentedTests:
    needs: build
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        api-level: [16, 21, 30]
        arch: [x86, x86_64]
        target: [default]

        include:
          - api-level: 30
            arch: x86
            target: google_apis
          - api-level: 30
            arch: x86_64
            target: google_apis

        exclude:
          - api-level: 16
            arch: x86_64

    steps:
      - uses: actions/checkout@v2

      - run: .github/do-prepare-aar-instrumented-tests

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/download-artifact@v2
        with:
          name: maven-local
          path: ~/.m2

      - uses: ViliusSutkus89/setup-android@release

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          target: ${{ matrix.target }}
          script: ./gradlew aar-instrumented-tests:connectedCheck

