name: release
on:
  release:
    types: [created, edited]

jobs:
  publishToMaven:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: maven-local
        path: ~/.m2

    - run: ls -lhaR ~/.m2
